server:
  port: 8080

spring:
  dataSource:
    platform: postGres
    URL: jdbc:postgresql://ec2-54-165-90-230.compute-1.amazonaws.com:5432/dchkugeens2l9r
    userName: paqcrhueujwxst
    password: d2d7494608fcd65d734fa1972204634c93991c56d3ad4dd1537a505a904e98cd
    driverClassName: org.postgresql.Driver
    initialization-mode: ALWAYS
    schema: CLASSPATH:/schema-postgresql.sql

  JPA:
  HIBERNATE:
  DDL-auto: create-drop